#!/bin/bash
for dir in $(find . -maxdepth 1 -type d); do
  for co in $(find $dir -mindepth 1 -type d); do
  if [ -f "$co/main.cpp" ] ;then
  mv "$co/main.cpp" "$(echo $co | tr "A-Z" "a-z").cpp"
  rm -rf $co
  fi
  done
done
